version: "3"
services:
  webserver:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./{{site_name}}:/var/www/{{site_name}}
      - ./apache_django.conf:/etc/apache2/sites-available/000-default.conf
      - ./startup.sh:/var/www/startup.sh
    command: server
